# Generated by Django 4.2.3 on 2023-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='preview')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='date of creation')),
                ('is_published', models.BooleanField(default=True, verbose_name='publish status')),
                ('count_of_views', models.PositiveIntegerField(default=0, editable=False, verbose_name='count of views')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'ordering': ('title',),
            },
        ),
    ]
