# Generated by Django 4.2.3 on 2023-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default='2000-10-24', verbose_name='created_at'),
        ),
    ]
