# Generated by Django 4.2.3 on 2023-07-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('slug', models.SlugField(default='', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='preview')),
                ('date_of_creation', models.DateField(verbose_name='date of creation')),
                ('count_of_views', models.IntegerField(verbose_name='count of views')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='category'),
        ),
    ]
