# Generated by Django 4.2.3 on 2023-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default='2003-10-23', verbose_name='created_at'),
        ),
    ]
